on:
  workflow_dispatch:

name: main

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NEWS_API: ${{ secrets.NEWS_API }}
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Run get_news_data.R
      run: |
        Rscript get_news_data.R
        DATE=$(date +'%Y-%m-%d')
        mv data.json data/$DATE.json

    # Commit the rendered R Markdown to the repo
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Updated data"
        file_pattern: mv data.json
